### ISSUE TITLE
deploy

### ISSUE THREAD

**Issue by rogivilela** [Soontao/cds-mysql#7] opened 2021-10-14 12:42 UTC
Hi again, 
when i change my entities, and try to migrate this to the db i receive the error below 
` code: 'ER_TABLE_EXISTS_ERROR',
  errno: 1050,
  sqlMessage: "Table 'my_proxymanager_histories' already exists",
  sqlState: '42S01',
  index: 0,
  sql: "CREATE TABLE `my_proxymanager_Histories` (`createdAt` timestamp NULL, `createdBy` varchar(255) NULL, `modifiedAt` timestamp NULL, `modifiedBy` varchar(255) NULL, `ID` varchar(36) NOT NULL, `entry_ID` varchar(36) NULL, `hours` int NULL, PRIMARY KEY (`ID`)) ENGINE=InnoDB CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci'",
  query: "CREATE TABLE `my_proxymanager_Histories` (`createdAt` timestamp NULL, `createdBy` varchar(255) NULL, `modifiedAt` timestamp NULL, `modifiedBy` varchar(255) NULL, `ID` varchar(36) NOT NULL, `entry_ID` varchar(36) NULL, `hours` int NULL, PRIMARY KEY (`ID`)) ENGINE=InnoDB CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci'",
  parameters: []
`

are there any other way to update my DB from my entities ?
[2021-10-14T12_36_58_813Z-debug.log](https://github.com/Soontao/cds-mysql/files/7346484/2021-10-14T12_36_58_813Z-debug.log)

**Comment by Soontao** [comment] 2021-10-15 02:57
Hi @rogivilela, 

I've performed a quick test in my environment, and `cds-mysql` could automatically migrate schema with command `npm run deploy`. 
Could you provide more information ? like 
* the full error message when you execute the `npm run deploy` command
* a little bit about your data modeling, maybe it caused by the data modeling or other reasons.. 
* the version of `sap/cds`, `sap/cds-dk`, `cds-mysql` blabla

I also will test migration again in windows, lets works parallel. 

Regards,
Theo

**Comment by Soontao** [comment] 2021-10-19 04:50
HI @rogivilela,

sorry my late reply, I've tested in windows environment, but I still can not re-produce your issue, could you help to execute following scripts and report the log to me? 

1. clone repo and setup mysql env

```bash
git clone https://github.com/Soontao/odata-v4-cap-demo
cd odata-v4-cap-demo
```

2. setup `DEBUG` environment

for windows cmd

```cmd
set DEBUG=db
```
for windows powershell
```powershell
$env:DEBUG='db'
```

for linux/macos
```bash
export DEBUG='db'
```

3. deploy with schema change

```bash
git checkout v1
npm run deploy
git checkout v2
npm run deploy
```


Or maybe you can provide a sample repo, which can reproduce your problem.

Regards,
Theo

**Comment by Soontao** [comment] 2021-10-21 04:52
Hi @rogivilela, 

it seems there are some issues to get the metadata from mysql: 

could you help to check the metadata processing?

1. create a debug configuration for vscode

```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "cds deploy",
      "type": "node",
      "request": "launch",
      "program": "${workspaceFolder}/node_modules/cds-mysql/bin/cds-mysql-deploy.js",
      "skipFiles": [
        "<node_internals>/**"
      ],
      "envFile": "${workspaceFolder}/.env",
      "internalConsoleOptions": "openOnSessionStart",
      "console": "internalConsole",
      "autoAttachChildProcesses": true
    }
  ]
}
```

2. create a breakpoint on the file `node_modules/cds-mysql/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js` line 1810, and debug with the `cds deploy` profile
3. check the `dbTables` variable contains the `People` table or not.
![image](https://user-images.githubusercontent.com/10473459/138212963-936d8e6f-41c0-4946-9e60-a077646e2ccf.png)
4. if there is no tables in the `dbTables` variable, please re-run the debug and check the line, please go to the same file line 1755 to check the current database and table names information is match you configuration or not.

![image](https://user-images.githubusercontent.com/10473459/138213398-4fd859f3-39fb-4976-84ee-78e50952ec0a.png)

Really thanks for your cooperation ! :)

Regards,
Theo

**Comment by Soontao** [comment] 2021-11-28 09:19
closed by no more update

**Closed by Soontao** 2021-11-28 09:19 UTC
Labels: bug, help wanted, question
